### ISSUE TITLE
Steam controller just needs a package

### ISSUE THREAD

**Issue by castrojo** [ShadowApex/steamos-ubuntu#1]
On my new install installing the `steam-devices` package handled all the steam controller stuff, there's no need to mess with the udev rules or anything now. I think you'd be safe just installing the package.

**Comment by ShadowApex** [comment]
Nice! I didn't know this. I'll try testing it out and update the installation script.

**Comment by ShadowApex** [comment]
Fixed in commit 1f8c036de5f7228c2d2b3e11e0786c22189090f0
